<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('productos')->insert([
            [
                'nombre' => 'Sensor de Oxigeno Drager OxyTrace VE MX01049',
                'imagen' => 'productos/Drager OxyTrace VE MX01049.png',
                'descripcion' => 'sensor de oxigeno drager',
                'estado' => 'activo',
                'stock' => 1,
                'precio_referencial' => null,
                'categoria_id' => 2,
            ],
            [
                'nombre' => 'Sensor de OxigenoITGM',
                'imagen' => 'productos/ITGM-04.jpg',
                'descripcion' => 'sensor de oxigeno',
                'estado' => 'activo',
                'stock' => 1,
                'precio_referencial' => null,
                'categoria_id' => 2,
            ],
            [
                'nombre' => 'Sensor de OxigenoMAQUET Servo I - Servo S',
                'imagen' => 'productos/MAQUET SERVO I- SERVO S.jpg',
                'descripcion' => 'sensor de oxigeno maquet',
                'estado' => 'activo',
                'stock' => 1,
                'precio_referencial' => null,
                'categoria_id' => 2,
            ],
            [
                'nombre' => 'Sensor de Oxigeno Maquet',
                'imagen' => 'productos/MAQUET.jpg',
                'descripcion' => 'sensor de oxigeno maquet',
                'estado' => 'activo',
                'stock' => 1,
                'precio_referencial' => null,
                'categoria_id' => 2,
            ],
            [
                'nombre' => 'Sensor de Oxigeno MAX-250A',
                'imagen' => 'productos/MAX-250A.jpg',
                'descripcion' => 'sensor de oxigeno maxtec',
                'estado' => 'activo',
                'stock' => 1,
                'precio_referencial' => null,
                'categoria_id' => 2,
            ],
            [
                'nombre' => 'Sensor de Oxigeno MAX-250B',
                'imagen' => 'productos/MAX-250B.jpg',
                'descripcion' => 'sensor de oxigeno maxtec',
                'estado' => 'activo',
                'stock' => 1,
                'precio_referencial' => null,
                'categoria_id' => 2,
            ],
            [
                'nombre' => 'Sensor de Oxigeno MAX-250E',
                'imagen' => 'productos/MAX-250E.jpg',
                'descripcion' => 'sensor de oxigeno maxtec',
                'estado' => 'activo',
                'stock' => 1,
                'precio_referencial' => null,
                'categoria_id' => 2,
            ],
            [
                'nombre' => 'Sensor de Oxigeno MLF-19 GE',
                'imagen' => 'productos/MLF-19 GE.jpg',
                'descripcion' => 'sensor de oxigeno ge',
                'estado' => 'activo',
                'stock' => 1,
                'precio_referencial' => null,
                'categoria_id' => 2,
            ],
            [
                'nombre' => 'Sensor de Oxigeno MOX-3',
                'imagen' => 'productos/MOX-3.jpg',
                'descripcion' => 'sensor de oxigeno mox',
                'estado' => 'activo',
                'stock' => 1,
                'precio_referencial' => null,
                'categoria_id' => 2,
            ],
            [
                'nombre' => 'Sensor de Oxigeno PSR-11-915-4',
                'imagen' => 'productos/PSR-11-915-4.jpg',
                'descripcion' => 'sensor de oxigeno compatible',
                'estado' => 'activo',
                'stock' => 1,
                'precio_referencial' => null,
                'categoria_id' => 2,
            ],
            [
                'nombre' => 'Sensor de flujo X5 Drager',
                'imagen' => 'productos/Sensor de flujo X5 Drager.png',
                'descripcion' => 'sensor de flujo drager',
                'estado' => 'activo',
                'stock' => 1,
                'precio_referencial' => null,
                'categoria_id' => 2,
            ],
            [
                'nombre' => 'Transductor para ultrasonido Compatible Mindray C5-2S',
                'imagen' => 'productos/Compatible Mindray C5-2S.png',
                'descripcion' => 'transductor convexo para ultrasonido compatible mindray',
                'estado' => 'activo',
                'stock' => 1,
                'precio_referencial' => null,
                'categoria_id' => 3,
            ],
            [
                'nombre' => 'Transductor para ultrasonido Compatible Mindray Endocavitario',
                'imagen' => 'productos/Compatible Mindray Endocavitario.png',
                'descripcion' => 'transductor endocavitario para ultrasonido compatible mindray',
                'estado' => 'activo',
                'stock' => 1,
                'precio_referencial' => null,
                'categoria_id' => 3,
            ],
            [
                'nombre' => 'Transductor para ultrasonido Compatible Sonoscape L741',
                'imagen' => 'productos/Compatible Sonoscape L741.png',
                'descripcion' => 'transductor lineal para ultrasonido compatible sonoscape',
                'estado' => 'activo',
                'stock' => 1,
                'precio_referencial' => null,
                'categoria_id' => 3,
            ],
            [
                'nombre' => 'Transductor para ultrasonido Compatible Sonoscape SS1-2000 C344',
                'imagen' => 'productos/Compatible Sonoscape SS1-2000 C344.png',
                'descripcion' => 'transductor convexo para ultrasonido compatible sonoscape',
                'estado' => 'activo',
                'stock' => 1,
                'precio_referencial' => null,
                'categoria_id' => 3,
            ],
            [
                'nombre' => 'Brazalete de Adulto obeso una vía',
                'imagen' => 'productos/ADULTO OBESO UNA VIA.png',
                'descripcion' => 'brazalete nibp adulto obeso una via',
                'estado' => 'activo',
                'stock' => 1,
                'precio_referencial' => null,
                'categoria_id' => 4,
            ],
            [
                'nombre' => 'Brazalete de Adulto una vía',
                'imagen' => 'productos/ADULTO UNA VIA.png',
                'descripcion' => 'brazalete nibp adulto una via',
                'estado' => 'activo',
                'stock' => 1,
                'precio_referencial' => null,
                'categoria_id' => 4,
            ],
            [
                'nombre' => 'Brazalete doble vía infante a adulto extra largo',
                'imagen' => 'productos/BRAZALETES DOBLE VIA INFANTE A ADULTO EXTRA LARGO.png',
                'descripcion' => 'brazalete nibp doble via infante a adulto',
                'estado' => 'activo',
                'stock' => 1,
                'precio_referencial' => null,
                'categoria_id' => 4,
            ],
            [
                'nombre' => 'Brazalete Desechable doble vía #1',
                'imagen' => 'productos/DESECHABLE DOBLE VIA 1.png',
                'descripcion' => 'brazalete nibp desechable doble via',
                'estado' => 'activo',
                'stock' => 1,
                'precio_referencial' => null,
                'categoria_id' => 4,
            ],
            [
                'nombre' => 'Brazalete Desechable doble vía #2',
                'imagen' => 'productos/DESECHABLE DOBLE VIA 2.png',
                'descripcion' => 'brazalete nibp desechable doble via',
                'estado' => 'activo',
                'stock' => 1,
                'precio_referencial' => null,
                'categoria_id' => 4,
            ],
            [
                'nombre' => 'Brazalete Desechable doble vía #3',
                'imagen' => 'productos/DESECHABLE DOBLE VIA 3.png',
                'descripcion' => 'brazalete nibp desechable doble via',
                'estado' => 'activo',
                'stock' => 1,
                'precio_referencial' => null,
                'categoria_id' => 4,
            ],
            [
                'nombre' => 'Brazalete Desechable doble vía #4',
                'imagen' => 'productos/DESECHABLE DOBLE VIA 4.png',
                'descripcion' => 'brazalete nibp desechable doble via',
                'estado' => 'activo',
                'stock' => 1,
                'precio_referencial' => null,
                'categoria_id' => 4,
            ],
            [
                'nombre' => 'Brazalete Desechable doble vía #5',
                'imagen' => 'productos/DESECHABLE DOBLE VIA 5.png',
                'descripcion' => 'brazalete nibp desechable doble via',
                'estado' => 'activo',
                'stock' => 1,
                'precio_referencial' => null,
                'categoria_id' => 4,
            ],
            [
                'nombre' => 'Brazalete de NIBP neonato una vía desechable',
                'imagen' => 'productos/NIBP NEONATO UNA VIA DESECHABLE.webp',
                'descripcion' => 'brazalete nibp neonato desechable',
                'estado' => 'activo',
                'stock' => 1,
                'precio_referencial' => null,
                'categoria_id' => 4,
            ],
            [
                'nombre' => 'ECG Holter compatible GE SEER 7 DER',
                'imagen' => 'productos/ECG HOLTER COMPATIBLE  GE SEER 7 DER.jpg',
                'descripcion' => 'cable ecg holter compatible ge',
                'estado' => 'activo',
                'stock' => 1,
                'precio_referencial' => null,
                'categoria_id' => 5,
            ],
            [
                'nombre' => 'ECG Holter compatible Aloka Nihon Kohden',
                'imagen' => 'productos/ECG HOLTER COMPATIBLE ALOKA NIHON KOHDEN.png',
                'descripcion' => 'cable ecg holter compatible nihon kohden',
                'estado' => 'activo',
                'stock' => 1,
                'precio_referencial' => null,
                'categoria_id' => 5,
            ],
            [
                'nombre' => 'ECG Holter compatible Mortara H3+5 DER',
                'imagen' => 'productos/ECG HOLTER COMPATIBLE Mortara H35 DER.png',
                'descripcion' => 'cable ecg holter compatible mortara',
                'estado' => 'activo',
                'stock' => 1,
                'precio_referencial' => null,
                'categoria_id' => 5,
            ],
            [
                'nombre' => 'ECG Holter compatible MT 200 Schiller',
                'imagen' => 'productos/ECG HOLTER COMPATIBLE MT 200 SCHILLER.jpg',
                'descripcion' => 'cable ecg holter compatible schiller',
                'estado' => 'activo',
                'stock' => 1,
                'precio_referencial' => null,
                'categoria_id' => 5,
            ],
            [
                'nombre' => 'ECG Holter compatible Schiller MS-12',
                'imagen' => 'productos/ECG HOLTER COMPATIBLE SCHILLER MS-12.png',
                'descripcion' => 'cable ecg holter compatible schiller',
                'estado' => 'activo',
                'stock' => 1,
                'precio_referencial' => null,
                'categoria_id' => 5,
            ],
            [
                'nombre' => 'Electrocardiógrafos Cable troncal EKG',
                'imagen' => 'productos/CABLE TRONCAL EKG.png',
                'descripcion' => 'cable troncal para electrocardiografo',
                'estado' => 'activo',
                'stock' => 1,
                'precio_referencial' => null,
                'categoria_id' => 6,
            ],
            [
                'nombre' => 'Electrocardiógrafos Clamps ECG',
                'imagen' => 'productos/CLAMPS ECG.png',
                'descripcion' => 'clamps ecg para extremidades',
                'estado' => 'activo',
                'stock' => 1,
                'precio_referencial' => null,
                'categoria_id' => 6,
            ],
            [
                'nombre' => 'Electrocardiógrafos Electrodos de succión ECG',
                'imagen' => 'productos/Electrodos de succión ECG.png',
                'descripcion' => 'electrodos de succion para ecg',
                'estado' => 'activo',
                'stock' => 1,
                'precio_referencial' => null,
                'categoria_id' => 6,
            ],
            [
                'nombre' => 'Electrocardiógrafos Latiguillos ECG',
                'imagen' => 'productos/LATIGUILLOS.png',
                'descripcion' => 'latiguillos para cable ecg',
                'estado' => 'activo',
                'stock' => 1,
                'precio_referencial' => null,
                'categoria_id' => 6,
            ],
            [
                'nombre' => 'Electrocardiógrafos Tipos de ECG',
                'imagen' => 'productos/TIPOS DE ECG.png',
                'descripcion' => 'accesorios y cables para ecg',
                'estado' => 'activo',
                'stock' => 1,
                'precio_referencial' => null,
                'categoria_id' => 6,
            ],
            [
                'nombre' => 'Accesorios monitores fetales compatibles',
                'imagen' => 'productos/ACCESORIOS MONITORES FETALES COMPATIBLES CON COMEN PHILIPS EDAN BIOCARE BIOLIGHT.png',
                'descripcion' => 'accesorios para monitor fetal',
                'estado' => 'activo',
                'stock' => 1,
                'precio_referencial' => null,
                'categoria_id' => 7,
            ],
            [
                'nombre' => 'TOCO - FHR fetal compatible con EDAN',
                'imagen' => 'productos/TOCO - FHR FETAL COMPATIBLE CON EDAN.jpg',
                'descripcion' => 'sensor toco fhr para monitor fetal',
                'estado' => 'activo',
                'stock' => 1,
                'precio_referencial' => null,
                'categoria_id' => 7,
            ],
        ]);
    }
}
